#!/usr/bin/python3
"""
Factorize numbers into prime
"""
import sys


def factorize():
    """
    A function to (format n = p*q)
    """
    try:
        file = sys.argv[1]
        with open(file) as f:
            for line in f:
                line = int(line)
                if line % 2 == 0:
                        print("{}={}*{}".format(line, line // 2, 2))
                        continue
                i = 3
                while i < line // 2:
                    if line % i == 0:
                        print("{}={}*{}".format(line, line // i, i))
                        break
                    i = i + 2
                if i == (line // 2) + 1:
                    print("{}={}*{}".format(line, line, 1))
    except (IndexError):
        pass


factorize()
