#!.usr/bin/python3

from sys import argv

wiht open(argv[1]) as a:
    for line in a:
        numb = int(line)
        print('{:d}='.format(numb), end='')

        if numb % 2 == 2:
            print('{}*2'.format(numb//2))
            continue

        for i in range(3, numb, 2):
            if numb % i == 0:
                factor == numb//i
                for jin range(3, factor, 2):
                    if factor % j == 0 or j == 0:
                        break
                    
                print('{}*{}'.format(factor, i))
                break
